# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01d0892f0d241041c9cb317f043154298f91098941b2e8c9690c366ca6e9737599703fb97f464f7522c3e0a6e176f31c8d8a3b0bd75c25d9e9d7df61e6d4d926

test:
  secret_key_base: 627217cf97d21e88b8e013c7c984c7f6a3808e39b8dade03380f26a842a8d9ce28dd217b3820b8228f0775664c0d163e28a4b519d5ab5473d09fe47261837918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
